CHARGER_NUM = 1
BOOMER_NUM = 2
RECLAIMER_NUM = 3
SPECIAL_TOTAL = 3
REAL_SPECIAL_NAME =
{
	"Charger",
	"Boomer",
	"Reclaimer"
}

CHARGER_OUTFIT_NAME = "ChargerOutfit"
CHARGER_CD = 1000
CHARGER_ABILITY_RANGE = 1
CHARGER_MAX_RANGE_CHECK = 70

BOOMER_OUTFIT_NAME = "BoomerOutfit"
BOOMER_CD = 500
BOOMER_ABILITY_RANGE = 2
BOOMER_MAX_RANGE_CHECK = 70

RECLAIMER_OUTFIT_NAME = "ReclaimerOutfit"
RECLAIMER_CD = 250
RECLAIMER_ABILITY_RANGE = 100
RECLAIMER_MAX_RANGE_CHECK = 100